apiVersion: apps/v1
kind: Deployment
metadata:
  name: dunbfloo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dunbfloo
  template:
    metadata:
      labels:
        app: dunbfloo
    spec:
      containers:
      - image: okteto.dev/dunbfloo:latest
        name: dunbfloo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ee2c6db3-8847-485a-8a11-714ab7c88e53"
        - name: Vless_Path
          value: "/vl11huhih5"
        - name: Vmess_UUID
          value: "ee2c6db3-8847-485a-8a11-714ab7c88e53"
        - name: Vmess_Path
          value: "/vmfdhytky36"
        - name: Share_Path
          value: "/v2link"
